website/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, Response
import re
from .models import User, UserSettings, Notification
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
from sqlalchemy.orm.exc import UnmappedInstanceError
auth = Blueprint("auth", __name__)

data = {}


def get(element_name: str) -> str | None:
    """Shorthand for request.form.get()."""

    return request.form.get(element_name)


@auth.route("/sign-in", methods=["GET", "POST"])
def login() -> str | Response:
    """
    Login view function. Renders the login page (sign_in.html)
    and gets all the values of the input elements in the form,
    gets the user in DB by username and checks the password. Logs-in the user if
    it matches, flash() an error if not. 
    """
    # data = request.form
    if request.method == "POST":

        email = get("email")
        password = get("password")
        remember_me = get("remember-me")

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True if remember_me ==
                           "on" else False)
                return redirect(url_for("views.home"))
            else:
                flash("email and password do not match. Please try again",
                      category="error")
        else:
            flash("email does not exist.", category="error")

    return render_template("signin_page.html", user=current_user)


@auth.route("/logout")
@login_required
def logout() -> Response:
    """Logout view function. Logs-out the user from flask-login and redirects the user to the first_page."""
    logout_user()
    return redirect(url_for("views.home"))


@auth.route("/sign-up", methods=["GET", "POST"])
def sign_up() -> str | Response:
    """
    Sign up view function. Renders the sign-up page (sign_up.html) and
    if post request, gets the form elements's values, checks format of
    email address, username and both passwords. If everything checks out,
    it creates a new User in database and also a UserSettings row associated
    the User.
    """

    if request.method == "POST":
        # Get values from inputs
        email = get("email")
        username = get("username")
        first_name = get("first-name")
        last_name = get("last-name")
        password1 = get("password1")
        password2 = get("password2")
        remember_me = get("remember-me")
        promotional_emails = get("promotional-emails")

        teacher = False

        if first_name is not None:
            teacher = True

        # If it finds a user with the email address that the new user inputted,
        # it will tell them that the email already exists. Only 1 account can be
        # associated with an email.
        user = User.query.filter_by(email=email).first()
        if user:
            flash("Email already exists", category="error")

        elif len(email) < 7:
            flash("Email address is too short", category="error")

        # The following regex is an expression that matches all emails (source: https://www.tutorialspoint.com/checking-for-valid-email-address-using-regular-expressions-in-java)
        elif email not in re.compile(r"^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$").findall(email):
            flash("Email address does not meet standards", category="error")

        elif len(username) < 2:
            flash("Username is too short", category="error")

        elif password1 != password2:
            flash("Passwords do not match", category="error")

        # Password requirements: At least 8 characters and contains at least 1 number AND 1 special characters from below.
        elif len(password1) < 12:
            flash("Password should be min. 12 characters long", category="error")

        else:
            # Create new user filling in the inputted information
            new_user = User(
                username=username,
                first_name="" if not teacher else first_name,
                last_name="" if not teacher else last_name,
                description="",
                email=email,
                password=generate_password_hash(password1, method="pbkdf2:sha256"),
                phone_number="",
                two_FA=False,
                account_type="student" if not teacher else "teacher",
            )

            db.session.add(new_user)
            db.session.commit()

            # To make the UserSettings associated with the User,
            # it is necessary to get the User's id (primary key)
            # Since SQLAlchemy auto-generates an id in the DB, it is necessary to add and commit
            # the new user, so that the id is generated.
            new_user = User.query.filter_by(email=email).first()
            new_settings = UserSettings(
                user_id=new_user.id,
                security_emails=True,
                activity_emails=True,
                promotional_emails=True if promotional_emails == "on" else False
            )

            db.session.add(new_settings)
            db.session.commit()

            login_user(new_user, remember=True if remember_me ==
                       "on" else False)
            return redirect(url_for("views.home"))

    return render_template("signup_page.html", user=current_user)


@auth.route("/account_deletion", methods=["POST", "GET"])
def delete_account() -> str | Response:
    """
    Delete account view function. Renders the delete account page and
    checks inputted information. If it matches, it removes the User's settings,
    the users notifications and the account itself from the DB and redirects the user to first_page.html.
    """
    if request.method == "POST":
        user = User.query.filter_by(id=current_user.id).first()
        password = get("password")
        if check_password_hash(user.password, password):
            db.session.delete(UserSettings.query.filter_by(
                user_id=current_user.id).first())

            # Since the user might not have any of the things listed after when they delete their account,
            # it is possible that the line of code throws an UnmappedInstanceError, hence the try except.
            from .models import Appointment, Message, Post, Comment, PostReaction, CommentReaction
            for model in (Notification, Appointment, Message, Post, Comment, PostReaction, CommentReaction):
                try:
                    model.query.filter_by(user_id=current_user.id).delete()
                except UnmappedInstanceError:
                    continue

            db.session.delete(user)
            db.session.commit()
            return redirect(url_for("views.home"))
        else:
            flash("Incorrect password", category="error")

    return render_template("delete_account.html", user=current_user)


@auth.route("/save", methods=["POST"])
@login_required
def save_information() -> Response:
    """
    This function saves the account information
    that the user might have changed in the account.html page.
    """
    # email is immutable, the user cannot change it because the input is readonly.
    email = get("email")

    user = User.query.filter_by(email=email).first()

    user.username = get("username")
    user.first_name = get("first-name")
    user.last_name = get("last-name")
    user.gender = get("gender")
    user.birthday = get("birthday")
    user.description = get("description")
    user.phone_number = get("number")
    db.session.commit()

    return redirect(url_for("views.account"))


@auth.route("/forgot_password", methods=["POST", "GET"])
def forgot_password() -> str:
    """
    Unfinished function. Renders the forget_password.html page.
    """
    data["email"] = get("email")
    try:
        User.query.filter_by(email=data["email"]).first()
    except KeyError:
        flash("Email address doesn't exist", category="error")

    return render_template("forgot_password.html", user=current_user)


@auth.route("/verify_code", methods=["POST", "GET"])
def verify_code() -> str:
    """
    Renders the verify_code.html page.
    """
    return render_template("verify_code.html", user=current_user)


@auth.route("/reset_password", methods=["POST", "GET"])
def reset_password() -> str:
    """
    Unfinished function. Similar to auth.change_password (next function).
    Renders the reset_password.html page and would let the user change their password
    after having verified their identity by sending them an verification code via email.
    """
    if request.method == "POST":
        # email = get("email")
        password1 = get("password1")
        password2 = get("password2")

        if password1 != password2:
            flash("Passwords do not match", category="error")
        else:
            user = User.query.filter_by(email=data["email"]).first()
            user.password = generate_password_hash(password1, method="sha256")
            db.session.commit()

    return render_template("reset_password.html", user=current_user)


@auth.route("/change_password", methods=["POST", "GET"])
def change_password() -> str:
    """
    Renders the change_password.html page from the account.html page,
    which asks for the user's current password and their new password.
    If everything checks out, the old password is replaced by the new one.
    """
    if request.method == "POST":
        user = User.query.filter_by(email=current_user.email).first()

        password = get("password")
        if check_password_hash(user.password, password):
            password1 = get("password1")
            password2 = get("password2")
            if password1 != password2:
                flash("New passwords do not match", category="error")

website/templates/appointment.html
{% extends "base.html" %}


{% block title %}Take appointment{% endblock %}
{% block imports %}
<link rel="stylesheet" href="../static/styles/contact_us.css">


{% endblock %}
{% block background %} style="background-image: url('../static/resources/background.jpg');" {% endblock %}

{% block content %}
</nav>
<form id="inner-container" method="POST" style="margin-top: 5rem;" action="{{url_for('views.appointment')}}">
	<h1 class="main-title">New appointment</h1>
	<select name="teacher" required>
		<option value="default">Choose teacher</option>
		{% for teacher in teachers %}
			<option value="{{teacher.id}}">{{teacher.first_name}} {{teacher.last_name}}</option>
		{% endfor %}
	</select>
	<select name="subject" required>
		<option value="default">Choose subject</option>
		<option value="pricing-question">Mathematics</option>
		<option value="website-issue">Physics</option>
		<option value="other">Programming</option>
		<option value="other">Other</option>
	</select>
	<textarea name="description" cols="30" rows="10"
		placeholder="Small explanation about the purpose of the appointment" required></textarea>
	<input type="date" name="date" required>

	<span id="time-picker">
		<div>
			<label for="start-time">Start time:</label>
			<input type="time" name="start-time" placeholder="time" required>
		</div>
		<div>
			<label for="end-time">End time:</label>
			<input type="time" name="end-time" placeholder="time" required>
		</div>
	</span>
	<p>By clicking "Take appointment", you agree to the <a href="#">Privacy</a> and <a href="#">Terms of Service</a>.
	</p>
	<button type="submit">Take appointment</button>
</form>

{% endblock %}

website/templates/base.html
<!DOCTYPE html>


<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}Home{% endblock %} - Mathegramming</title>
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='styles/style.css')}}">
	<script src="{{url_for('static', filename='script/index.js')}}"></script>
	<link rel="icon" href="{{url_for('static', filename='mathegramming_logo.png')}}">
	{% block imports %}
	{% endblock %}
</head>

<body {% block background %}{%endblock %}>
	<nav class="topnav">
		<div class="left-nav">
			<a class="active" href="{{ url_for('views.home') }}">
				<img class="main-logo" src="{{ url_for('static', filename='resources/mathegramming_logo.png') }}"
					alt="MG">
			</a>
			<a href="{{url_for('views.contact_us')}}">Contact Us</a>
			<a href="{{url_for('views.pricing')}}">Pricing</a>
			<a href="{{url_for('views.about_us')}}">About Us</a>
		</div>
		<div class="right-nav">



			{% if current_user.is_authenticated %}
				<a href="{{url_for('views.appointment')}}">Appointment</a>
				<a href="{{url_for('views.forum')}}">Forum</a>
				<details class="notification-details">
					<summary class="notification-summary"><img
							src="{{ url_for('static', filename='resources/bell_icon.png') }}" alt="Notifications"
							class="notification-image"></summary>
					<form class="notifications" method="POST" action="/clear_all_notifications">
						<div class="notification-content">
							{% if current_user.notifications %}
								{% for notif in current_user.notifications[::-1] %}
									<a href="{{notif.link}}">
										<button class="notification-button" type="button">
											<h3 style="margin: auto;">{{notif.title}}</h3>
											<p style="font-size: .9rem;">{{notif.description}}</p>
										</button>
									</a>
								{% endfor %}
							{% else %}
								<p style="color: var(--text-bg);">You have no notifications</p>
							{% endif %}
						</div>
						<button type="button" id="mark-read" onClick="eraseAll(1)" method="POST">Mark all as read</button>
					</form>
				</details>
				<a href="{{url_for('views.account')}}" class="account">
					<div class="pfp1"></div>
				</a>
			{% else %}
				{% block nav_bar_item %}
					<a href="{{url_for('auth.sign_up')}}">Sign up</a>
					<a href="{{url_for('auth.login')}}">Sign in</a>
				{% endblock %}
			{% endif %}
		</div>

	</nav>

	<div id="outer-container">
		{% block content %}
		{% endblock %}
	</div>


	<footer>
		<a href="#" class="footer-links">Terms and Conditions</a>
		<a href="#" class="footer-links">Privacy policy</a>
		<a href="{{url_for('views.contact_us')}}" class="footer-links">Report a problem</a>
		<a href="{{url_for('views.contact_us')}}" class="footer-links">Contact us</a>
		<a href="{{url_for('views.about_us')}}" class="footer-links">About us</a>
	</footer>
</body>

</html>

website/templates/change_password.html
{% extends "base.html" %}

{% block title %}Change password {% endblock %}

{% block imports %}
<link rel="stylesheet" href="../static/styles/authentication.css">
<link rel="stylesheet" href="../static/styles/forgot_password.css">
{% endblock %}
{% block background %} style="background-image: url('../static/resources/background.jpg');" {%endblock %}

{% block content %}

<form class="inner-container" method="POST">
	<h1>Change password</h1>

	<input type="password" name="password" placeholder="Password">
	<input type="password" name="password1" placeholder="New password">
	<input type="password" name="password2" placeholder="Confirm new password">

	{% with messages = get_flashed_messages(with_categories=true) %}
		{% if messages %}
			{% for category, message in messages %}
				{% if category == "error" %}
					<p class="alert">{{ message }}</p>
				{% endif %}
			{% endfor %}
		{% endif %}
	{% endwith %}

	<button type="submit">Reset my password</button>
</form>


{% endblock %}

website/templates/contact_us.html
{% extends "base.html" %}


{% block title %}Contact us{% endblock %}
{% block imports %}
<link rel="stylesheet" type="text/css" href="../static/styles/contact_us.css">
{% endblock %}

{% block background %} style="background-image: url('../static/resources/background.jpg');" {%endblock %}

{% block content %}

<form id="inner-container" method="POST" action="{{url_for('views.contact_us')}}">
	<h1 id="main-title">Send us a message</h1>
	<input type="tel" name="phone-number" placeholder="Phone number *" required>
	<select name="reason" required>
		<option value="default">Select the reason why you are reaching us</option>
		<option value="pricing-question">Ask a pricing-related question</option>
		<option value="website-issue">Report an issue with the website</option>
		<option value="other">Other</option>
	</select>
	<input type="text" name="title" placeholder="Title *" required>
	<textarea name="message" cols="30" rows="10" placeholder="Message *" required></textarea>
	<p>By clicking "Send message", you agree to the <a href="#">Privacy</a> and <a href="#">Terms of Service</a>.</p>
	<button type="submit">Send message</button>
</form>

{% endblock %}

website/templates/delete_account.html
{% extends "base.html" %}

{% block title %}Account deletion{% endblock %}

{% block imports %}
<link rel="stylesheet" href="../static/styles/authentication.css">
<link rel="stylesheet" href="../static/styles/account_deletion.css">
{% endblock %}
{% block background %} style="background-image: url('../static/resources/background.jpg');" {%endblock %}

{% block content %}

<form class="inner-container" method="POST" action="{{url_for('auth.delete_account')}}">
	<h1>Account deletion</h1>
	<p style="color: white; margin: 0;">This action is irreversible!</p>

	<input type="password" class="inputs" name="password" placeholder="Password">
	{% with messages = get_flashed_messages(with_categories=true) %}
		{% if messages %}
			{% for category, message in messages %}
				{% if category == "error" %}
					<p class="alert" style="margin: 0;">{{ message }}</p>
				{% endif %}
			{% endfor %}
		{% endif %}
	{% endwith %}
	<button type="submit" method="POST" id="delete">Delete account</button>
</form>

{% endblock %}

website/templates/email_prefs.html
{% extends "base.html" %}


{% block title %}Email preferences{% endblock %}
{% block imports %}
<link rel="stylesheet" href="../static/styles/bootstrap_switch.css">
<link rel="stylesheet" href="../static/styles/account.css">
<link rel="stylesheet" href="../static/styles/email_prefs.css">
<script>
	window.onload = function () {
		const inputs = document.querySelector("input[class='checkbox']")
		inputs.forEach(input => {
			console.log()
		})
	}
</script>
{% endblock %}
{% block content %}
<details class="details">
	<summary class="summary"><img src="../static/resources/hamburger_icon.png" alt="Show sidebar"></summary>
	<div class="sidebar">
		<div style="padding-bottom: 4rem;">
			<div class="profile-area-sidebar">
				<div class="profile-picture-sidebar"></div>
				<h2>
					{% if current_user.first_name not in ("None", "") and current_user.last_name not in ("None", "") %}
						{{current_user.first_name}} {{current_user.last_name}}
					{% else %}
						{{current_user.username}}
					{% endif %}
				</h2>
			</div>

			<a href="{{url_for('views.account')}}"><button>Account profile</button></a>
			<a href="{{url_for('views.activity_information')}}"><button>Acitivity information</button></a>
			<a href="{{url_for('views.appearance')}}"><button>Appearance</button></a>
			<a href="{{url_for('views.email_prefs')}}"><button>Email preferences</button></a>
			<a href="{{url_for('auth.logout')}}"><button>Logout</button></a>
		</div>
	</div>
</details>

<div class="sidebar normal-sidebar">
	<div style="padding-bottom: 4rem;">
		<div class="profile-area-sidebar">
			<div class="profile-picture-sidebar"></div>
			<h2>
				{% if current_user.first_name not in ("None", "") and current_user.last_name not in ("None", "") %}
					{{current_user.first_name}} {{current_user.last_name}}
				{% else %}
					{{current_user.username}}
				{% endif %}
			</h2>
		</div>

		<a href="{{url_for('views.account')}}"><button>Account profile</button></a>
		<a href="{{url_for('views.activity_information')}}"><button>Acitivity information</button></a>
		<a href="{{url_for('views.appearance')}}"><button>Appearance</button></a>
		<a href="{{url_for('views.email_prefs')}}"><button>Email preferences</button></a>
		<a href="{{url_for('auth.logout')}}"><button>Logout</button></a>
	</div>
</div>
<div class="fixed-shadow"></div>


<form method="POST" id="inner-container">
	<h1>Email preferences</h1>

	<div class="form-check form-switch">
		<label class="form-check-label" for="flexSwitchCheckDefault">Get security related emails</label>
		<input class="form-check-input exclude" type="checkbox" id="flexSwitchCheckDefault" name="security-emails">
	</div>
	<div class="form-check form-switch">
		<label class="form-check-label" for="flexSwitchCheckDefault">Get an email when you get an answer to your
			question</label>
		<input class="form-check-input exclude" type="checkbox" id="flexSwitchCheckDefault" name="activity-emails">
	</div>
	<div class="form-check form-switch">
		<label class="form-check-label" for="flexSwitchCheckDefault">Get promotional emails from Mathegramming</label>
		<input class="form-check-input exclude" type="checkbox" id="flexSwitchCheckDefault" name="promotional-emails">
	</div>

	<button type="submit">Save</button>

</form>


{% endblock %}

website/templates/forgot_password.html
{% extends "base.html" %}

{% block title %}Forgot password {% endblock %}

{% block imports %}
<link rel="stylesheet" href="../static/styles/authentication.css">
<link rel="stylesheet" href="../static/styles/forgot_password.css">
{% endblock %}
{% block background %} style="background-image: url('../static/resources/background.jpg');" {%endblock %}

{% block content %}

<form class="inner-container" method="POST">
	<h1>Forgot password</h1>
	<p>We are going to send to your email address a verification code</p>
	<input type="email" name="email" placeholder="Email address">

	{% with messages = get_flashed_messages(with_categories=true) %}
		{% if messages %}
			{% for category, message in messages %}
				{% if category == "error" %}
					<p class="alert">{{ message }}</p>
				{% endif %}
			{% endfor %}
		{% endif %}
	{% endwith %}

	<a href="{{url_for('auth.verify_code')}}"><button type="submit">Send verification code</button></a>
</form>


{% endblock %}

website/templates/home.html
{% extends "base.html" %}


{% block title %}Welcome{% endblock %}
{% block imports %}
<link rel="stylesheet" href="../static/styles/home.css">
{% endblock %}

{% block background %} style="background-image: url('../static/resources/background.jpg');" {% endblock %}

{% block content %}
<div id="container">
	<img src="../static/resources/mathegramming_logo.png" alt="">
	<div>
		<h1 id="main-title">Mathegramming</h1>
		<div id="content">
			<p>Catchphrase here</p>
			<ul>
				<li>Learn Mathematics</li>
				<li>Learn Physics</li>
				<li>Learn Programming</li>
				<li>Learn how to use them together</li>
			</ul>
		</div>
	</div>
	<div id="buttons">
		{% if current_user.is_authenticated %}
		<a href="{{url_for('views.appointment')}}" style="flex: 2; order: 1;">
			<button class="button hover-style important">New appointment</button>
		</a>
			<a href="{{url_for('views.exercises')}}" style="flex: 1; order: 2;">
				<button class="button hover-style">Exercises</button>
			</a>
		{% else %}
			<a href="{{url_for('auth.sign_up')}}" class="sign-buttons-landscape" style="flex: 1;">
				<button class="button hover-style">Sign up</button>
			</a>
			<a href="{{url_for('views.pricing')}}" style="flex: 2;">
				<button class="button hover-style important">Pricing</button>
			</a>
			<a href="{{url_for('auth.login')}}" class="sign-buttons-landscape" style="flex: 1;">
				<button class="button hover-style">Sign in</button>
			</a>
			<div id="sign-buttons-portrait">
				<a href="{{url_for('auth.sign_up')}}" style="flex: 1;">
					<button class="button hover-style">Sign up</button>
				</a>
				<a href="{{url_for('auth.login')}}" style="flex: 1;">
					<button class="button hover-style">Sign in</button>
				</a>
			</div>
		{% endif %}
	</div>
</div>
{% endblock %}

website/templates/signin_page.html
{% extends "base.html" %}


{% block title %}Sign in - Mathegramming{% endblock %}
{% block imports %}
<link rel="stylesheet" type="text/css" href="../static/styles/bootstrap_checkbox.css">
<link rel="stylesheet" type="text/css" href="../static/styles/authentication.css">
{% endblock %}


{% block nav_bar_item %}
<a href="{{url_for('auth.sign_up')}}" style="float: right;">Sign up</a>
{% endblock %}
{% block background %} style="background-image: url('../static/resources/background.jpg');" {%endblock %}
{% block content %}
<form class="inner-container" method="POST">
	<h1>Login into<br>your account</h1>

	<div style="display: flex; column-gap: 1ch; width: 100%">
		<a href="https://www.google.com">
			<button>
				<div class="sign-as">
					<img src="../static/resources/google_logo.png" alt="" width="30px">
					Google
				</div>
			</button>
		</a>
		<a href="https://www.microsoft.com">
			<button>
				<div class="sign-as">
					<img src="../static/resources/microsoft_logo.png" alt="" width="30px">
					Microsoft
				</div>
			</button>
		</a>
	</div>

	<hr class="solid" />
	<input type="email" placeholder="Email" class="inputs" name="email">
	<input type="password" placeholder="Password" class="inputs" name="password">

	<div class="form-check" style="display: flex; align-items: center; column-gap: 1rem">
		<input class="form-check-input" type="checkbox" id="remember-me" class="checkbox" name="remember-me">
		<label class="form-check-label" for="remember-me">
			Remember me
		</label>
	</div>

	{% with messages = get_flashed_messages(with_categories=true) %}
		{% if messages %}
			{% for category, message in messages %}
				{% if category == "error" %}
					<p class="alert">{{ message }}</p>
				{% endif %}
			{% endfor %}
		{% endif %}
	{% endwith %}

	<br>
	<button type="submit" style="color: var(--text-bg-inv);">Login</button>
	<a href="{{url_for('auth.forgot_password')}}" class="forgot-password">Forgot password</a>

</form>


{% endblock %}

website/templates/signup_page.html
{% extends "base.html" %}

{% block imports %}
<link rel="stylesheet" type="text/css" href="../static/styles/bootstrap_checkbox.css">
<link rel="stylesheet" type="text/css" href="../static/styles/authentication.css">
<link rel="stylesheet" type="text/css" href="../static/styles/signup_page.css">

{% endblock %}

{% block nav_bar_item %}
<a href="{{url_for('auth.login')}}" style="float: right;">Sign in</a>
{% endblock %}

{% block background %} style="background-image: url('../static/resources/background.jpg');" {%endblock %}
{% block content %}
<form class="inner-container" id="inner-container_student" method="POST">
	<h1>Create a <br> student account</h1>

	<div style="display: flex; column-gap: 1ch; width: 100%">
		<a href="https://www.google.com">
			<button>
				<div class="sign-as">
					<img src="../static/resources/google_logo.png" alt="" width="27px">
					Google
				</div>
			</button>
		</a>
		<a href="https://www.microsoft.com">
			<button style="height: 100%;">
				<div class="sign-as">
					<img src="../static/resources/microsoft_logo.png" alt="" width="22px">
					Microsoft
				</div>
			</button>
		</a>
	</div>


	<hr class="solid" />
	<input type="text" placeholder="Email" class="inputs" name="email">
	<input type="text" placeholder="Username" class="inputs" name="username">
	<input type="password" placeholder="Password" class="inputs" name="password1">
	<input type="password" placeholder="Confirm Password" class="inputs" name="password2">

	<div class="form-check" style="display: flex; align-items: center; column-gap: 1rem">
		<input class="form-check-input" type="checkbox" value="" id="remember-me-student" name="remember-me">
		<label class="form-check-label" for="remember-me-student" class="remember-me">
			Remember me
		</label>
	</div>
	<div class="form-check" style="display: flex; align-items: center; column-gap: 1rem">
		<input class="form-check-input" type="checkbox" value="" id="promotional-emails-student"
			name="promotional-emails">
		<label class="form-check-label" for="promotional-emails-student" class="remember-me">
			Receive promotional emails
		</label>
	</div>

	{% with messages = get_flashed_messages(with_categories=true) %}
		{% if messages %}
			{% for category, message in messages %}
				{% if category == "error" %}
					<p class="alert">{{ message }}</p>
				{% endif %}
			{% endfor %}
		{% endif %}
	{% endwith %}
	<br>
	<button type="submit" style="color: var(--text-bg-inv);">Create account</button>

</form>


<form class="inner-container" id="inner-container_teacher" method="POST">
	<h1>Create a<br>teacher account</h1>

	<div style="display: flex; column-gap: 1ch; width: 100%">
		<a href="https://www.google.com">
			<button>
				<div class="sign-as">
					<img src="../static/resources/google_logo.png" alt="" width="27px">
					Google
				</div>
			</button>
		</a>
		<a href="https://www.microsoft.com">
			<button style="height: 100%; padding: 0.5em;">
				<div class="sign-as">
					<img src="../static/resources/microsoft_logo.png" alt="" width="22px">
					Microsoft
				</div>
			</button>
		</a>
	</div>

	<hr class="solid" />
	<input type="text" placeholder="Email" class="inputs" name="email">
	<input type="text" placeholder="Username" class="inputs" name="username">
	<input type="text" placeholder="First name" class="inputs" name="first-name">
	<input type="text" placeholder="Last name" class="inputs" name="last-name">
	<input type="password" placeholder="Password" class="inputs" name="password1">
	<input type="password" placeholder="Confirm Password" class="inputs" name="password2">

	<div class="form-check" style="display: flex; align-items: center; column-gap: 1rem">
		<input class="form-check-input" type="checkbox" value="" id="remember-me-teacher" class="remember-me"
			name="remember-me">
		<label class="form-check-label" for="remember-me-teacher">
			Remember me
		</label>
	</div>
	<div class="form-check" style="display: flex; align-items: center; column-gap: 1rem">
		<input class="form-check-input" type="checkbox" value="" id="promotional-emails-teacher"
			name="promotional-emails">
		<label class="form-check-label" for="promotional-emails-teacher">
			Receive promotional emails
		</label>
	</div>


	{% with messages = get_flashed_messages(with_categories=true) %}
		{% if messages %}
			{% for category, message in messages %}
				{% if category == "error" %}
					<p class="alert">{{ message }}</p>
				{% endif %}
			{% endfor %}
		{% endif %}
	{% endwith %}
	<br>
	<button type="submit" style="color: var(--text-bg-inv);">Create account</button>

</form>


{% endblock %}

website/templates/terms_of_service.html
{% extends "base.html" %}

{% block title %}Terms of service{% endblock %}

{% block imports %}

{% endblock %}
{% block content %}

{% endblock %}

website/templates/verify_code.html
{% extends "base.html" %}

{% block title %}Forgot password {% endblock %}

{% block imports %}
<link rel="stylesheet" href="../static/styles/authentication.css">
<link rel="stylesheet" href="../static/styles/forgot_password.css">
{% endblock %}
{% block background %} style="background-image: url('../static/resources/background.jpg');" {%endblock %}

{% block content %}

<form class="inner-container" style="max-width: 20%;" method="POST">
	<h1>Verification code</h1>
	<p>Enter the verification code that was sent to your email address. It will expire in 10 minutes.</p>
	<input type="text" placeholder="Ex: FDS-ALR-NVC" style="text-align: center;">

	{% with messages = get_flashed_messages(with_categories=true) %}
		{% if messages %}
			{% for category, message in messages %}
				{% if category == "error" %}
					<p class="alert">{{ message }}</p>
				{% endif %}
			{% endfor %}
		{% endif %}
	{% endwith %}

	<a href="{{url_for('auth.reset_password')}}"><button type="submit">Confirm verification code</button></a>
</form>


{% endblock %}